#!/usr/bin/env bash

# gates-of-tartaros – Minimal replacement for agetty with SSH support
# 
# Copyright © 2013  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [ "$1" = "-" ]; then
    tty="$2"
    shift 2
    
    export "$@"
    
    display_function=_display
    read_function=_read
    login_function=_login
    
    function _display
    {
	echo -en '\e[H\e[2J'
	echo -e "\e[${ANSI_COLOR}m${NAME} (${tty})\e[00m"
	echo
	echo -n 'Login: '
    }
    
    function _read
    {
	read user
    }
    
    function _login
    {
	if [ ! "${user/@/}" = "${user}" ]; then
	    export GOT_COMMAND="@ssh@ ${user}"
	    login -p -f @sshlogin@
	elif [ "${user::1}" = "-" ]; then
	    stty -icanon -echo -isig -ix{on,off,any}
	    echo $'\e[01;31mNice try! Sleeping for 10 minutes...\e[00m'
	    sleep 600
	else
	    login -- "${user}"
	fi
    }
    
    NAME="$(uname -o)"
    ANSI_COLOR='01;34' # must be exactly ANSI_COLOR as it is defined in /etc/os-release
    if [ -f "@etc@/os-release" ]; then
	. "@etc@/os-release"
    fi
    if [ -f "@etc@/@command@rc" ]; then
	.  "@etc@/@command@rc"
    fi
    
    $display_function
    $read_function
    $login_function
else
    # cannot get any other solution to work with `login`
    # than to spawn a new process with the pipes pre-set
    
    tty="@dev@/$1"
    tty_settings="$(stty --save)"
    "$0" - "$@" > "${tty}" 2> "${tty}" < "${tty}"
    stty "${tty_settings}"
fi

