#!/usr/bin/env bash

# gates-of-tartaros – Minimal replacement for agetty with SSH support
# 
# Copyright © 2013  Mattias Andrée (maandree@member.fsf.org)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Read the parameters: the first is the tty, the rest are exports
tty="$1"
shift 1
export "$@"

# Change TTY
exec 0<&-
exec 1<&-
exec 2<&-
exec 0<>"@dev@${tty}"
exec 1>&0
exec 2>&0


# Store TTY settings so they can be restorted for the next run
tty_settings="$(stty --save)"


# Function used for printing information on the terminal for the user
display_function=_display
function _display
{
    echo -en '\e[H\e[2J'
    echo -e "\e[${ANSI_COLOR}m${NAME} (${tty})\e[00m"
    echo
    echo -n 'Login: '
}

# Function for reading the username form the terminal
read_function=_read
function _read
{
    read user
}

# Function for logging in the user
login_function=_login
function _login
{
    if [ ! "${user/@/}" = "${user}" ]; then
	export GOT_COMMAND="@ssh@ ${user}"
	setsid -c login -p -f @sshlogin@
    elif [ "${user::1}" = "-" ]; then
	stty -icanon -echo -isig -ix{on,off,any}
	echo $'\e[01;31mNice try! Sleeping for 10 minutes...\e[00m'
	sleep 600
    else
	setsid -c login -- "${user}"
    fi
}


# Load OS information and extensions
NAME="$(uname -o)"
ANSI_COLOR='01;34' # must be exactly ANSI_COLOR as it is defined in /etc/os-release
if [ -f "@etc@os-release" ]; then
    . "@etc@os-release"
fi
if [ -f "@etc@@command@rc" ]; then
    .  "@etc@@command@rc"
fi

# Let the user log in
$display_function
$read_function
$login_function

# Restore the TTY settings for the next run
stty "${tty_settings}"

